In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("encoding_practice_dataset.csv")

In [3]:
df.head()

,user_id,gender,education_level,job_role,city,marital_status,device_type,subscription_plan,payment_method,monthly_income,tenure_months,churn
0,U1,Male,High School,Sales,City_38,Divorced,Mobile,Standard,Wallet,37784,24,0
1,U2,Female,Bachelor,Doctor,City_18,Married,Tablet,Standard,UPI,127167,27,0
2,U3,Female,Master,Sales,City_26,Married,Tablet,Free,Cash,82359,37,1
3,U4,Female,Bachelor,Consultant,City_6,Widowed,Mobile,Standard,Wallet,93608,39,0
4,U5,Male,Master,HR,City_4,Divorced,Laptop,Premium,Net Banking,30111,63,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1000 non-null   object
 1   gender             1000 non-null   object
 2   education_level    1000 non-null   object
 3   job_role           1000 non-null   object
 4   city               1000 non-null   object
 5   marital_status     1000 non-null   object
 6   device_type        1000 non-null   object
 7   subscription_plan  1000 non-null   object
 8   payment_method     1000 non-null   object
 9   monthly_income     1000 non-null   int64
 10  tenure_months      1000 non-null   int64
 11  churn              1000 non-null   int64
dtypes: int64(3), object(9)
memory usage: 93.9+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
df['gender_label'] = le.fit_transform(df['gender'])
df[['gender', 'gender_label']].head()

   gender  gender_label
0    Male             1
1  Female             0
2  Female             0
3  Female             0
4    Male             1

In [7]:
df_onehot = pd.get_dummies(df, columns=['marital_status'])
df_onehot.head()

,user_id,gender,education_level,job_role,city,device_type,subscription_plan,payment_method,monthly_income,tenure_months,churn,gender_label,marital_status_Divorced,marital_status_Married,marital_status_Single,marital_status_Widowed
0,U1,Male,High School,Sales,City_38,Mobile,Standard,Wallet,37784,24,0,1,True,False,False,False
1,U2,Female,Bachelor,Doctor,City_18,Tablet,Standard,UPI,127167,27,0,0,False,True,False,False
2,U3,Female,Master,Sales,City_26,Tablet,Free,Cash,82359,37,1,0,False,True,False,False
3,U4,Female,Bachelor,Consultant,City_6,Mobile,Standard,Wallet,93608,39,0,0,False,False,False,True
4,U5,Male,Master,HR,City_4,Laptop,Premium,Net Banking,30111,63,0,1,True,False,False,False

In [8]:
df['education_level'].unique()

array(['High School', 'Bachelor', 'Master', 'PhD', 'Diploma'],
      dtype=object)

In [9]:
df['education_level'] = df['education_level'].astype(str)
df['education_level'] = df['education_level'].str.strip()
df['education_level'] = df['education_level'].str.title()

In [10]:
print(df['education_level'].unique())

['High School' 'Bachelor' 'Master' 'Phd' 'Diploma']

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
order = [['High School', 'Diploma', 'Bachelor', 'Master', 'Phd']]

In [13]:
oe = OrdinalEncoder(
    categories=order,
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

In [14]:
df['education_ordinal'] = oe.fit_transform(df[['education_level']])

In [15]:
print(df[['education_level', 'education_ordinal']].drop_duplicates())

   education_level  education_ordinal
0      High School                0.0
1         Bachelor                2.0
2           Master                3.0
11             Phd                4.0
21         Diploma                1.0

In [16]:
job_role_mean = df.groupby('job_role')['churn'].mean()
df['job_role_target'] = df['job_role'].map(job_role_mean)
df[['job_role', 'job_role_target']].head()

     job_role  job_role_target
0       Sales         0.280899
1      Doctor         0.201835
2       Sales         0.280899
3  Consultant         0.254545
4          HR         0.292683

In [17]:
freq_map = df['payment_method'].value_counts()
df['payment_method_freq'] = df['payment_method'].map(freq_map)
df[['payment_method', 'payment_method_freq']].head()

  payment_method  payment_method_freq
0         Wallet                  163
1            UPI                  164
2           Cash                  153
3         Wallet                  163
4    Net Banking                  158

In [18]:
import category_encoders as ce

In [19]:
import numpy as np

In [20]:
print(df.columns)
df.info()

Index(['user_id', 'gender', 'education_level', 'job_role', 'city',
       'marital_status', 'device_type', 'subscription_plan', 'payment_method',
       'monthly_income', 'tenure_months', 'churn', 'gender_label',
       'education_ordinal', 'job_role_target', 'payment_method_freq'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              1000 non-null   object
 1   gender               1000 non-null   object
 2   education_level      1000 non-null   object
 3   job_role             1000 non-null   object
 4   city                 1000 non-null   object
 5   marital_status       1000 non-null   object
 6   device_type          1000 non-null   object
 7   subscription_plan    1000 non-null   object
 8   payment_method       1000 non-null   object
 9   monthly_income       1000 non-null   int64
 10  tenure_months        1000 non-null   int64
 11  churn                1000 non-null   int64
 12  gender_label         1000 non-null   int64
 13  education_ordinal    1000 non-null   float64
 14  job_role_target      1000 non-null   float64
 15  payment_method_freq  1000 non-null   int64
dtypes: float64(2), int64(5), object(9)
memory usage: 125.1+ KB

In [21]:
be = ce.BinaryEncoder(cols=['city'])
df_binary = be.fit_transform(df)

In [22]:
print(df_binary.columns)

Index(['user_id', 'gender', 'education_level', 'job_role', 'city_0', 'city_1',
       'city_2', 'city_3', 'city_4', 'city_5', 'marital_status', 'device_type',
       'subscription_plan', 'payment_method', 'monthly_income',
       'tenure_months', 'churn', 'gender_label', 'education_ordinal',
       'job_role_target', 'payment_method_freq'],
      dtype='object')

In [23]:
df_no_city = df.drop(columns=['city'])

In [24]:
city_binary_cols = [c for c in df_binary.columns if c.startswith('city_')]

In [25]:
df_final = pd.concat(
[df_no_city, df_binary[city_binary_cols]],
axis=1
)

In [26]:
print(df_final.columns)
df_final.head()

Index(['user_id', 'gender', 'education_level', 'job_role', 'marital_status',
       'device_type', 'subscription_plan', 'payment_method', 'monthly_income',
       'tenure_months', 'churn', 'gender_label', 'education_ordinal',
       'job_role_target', 'payment_method_freq', 'city_0', 'city_1', 'city_2',
       'city_3', 'city_4', 'city_5'],
      dtype='object')

,user_id,gender,education_level,job_role,marital_status,device_type,subscription_plan,payment_method,monthly_income,tenure_months,...,gender_label,education_ordinal,job_role_target,payment_method_freq,city_0,city_1,city_2,city_3,city_4,city_5
0,U1,Male,High School,Sales,Divorced,Mobile,Standard,Wallet,37784,24,...,1,0.0,0.280899,163,0,0,0,0,0,1
1,U2,Female,Bachelor,Doctor,Married,Tablet,Standard,UPI,127167,27,...,0,2.0,0.201835,164,0,0,0,0,1,0
2,U3,Female,Master,Sales,Married,Tablet,Free,Cash,82359,37,...,0,3.0,0.280899,153,0,0,0,0,1,1
3,U4,Female,Bachelor,Consultant,Widowed,Mobile,Standard,Wallet,93608,39,...,0,2.0,0.254545,163,0,0,0,1,0,0
4,U5,Male,Master,HR,Divorced,Laptop,Premium,Net Banking,30111,63,...,1,3.0,0.292683,158,0,0,0,1,0,1