In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("customer_churn_encoding_1000.csv")

In [3]:
df.head()

,Age,Monthly_Charges,Tenure_Months,Contract_Type,Internet_Service,Payment_Method,Region,Tech_Support,Churn
0,56,73.26,5,One-year,DSL,Credit Card,South,No,0
1,69,44.25,65,Two-year,DSL,Credit Card,South,No,0
2,46,46.92,30,Month-to-month,DSL,Debit Card,North,Yes,1
3,32,57.73,21,Two-year,DSL,UPI,North,Yes,0
4,60,22.01,70,Month-to-month,DSL,Credit Card,East,No,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1000 non-null   int64
 1   Monthly_Charges   1000 non-null   float64
 2   Tenure_Months     1000 non-null   int64
 3   Contract_Type     1000 non-null   object
 4   Internet_Service  906 non-null    object
 5   Payment_Method    1000 non-null   object
 6   Region            1000 non-null   object
 7   Tech_Support      1000 non-null   object
 8   Churn             1000 non-null   int64
dtypes: float64(1), int64(3), object(5)
memory usage: 70.4+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df['Payment_Method_label'] =le.fit_transform(df['Payment_Method'])
df[['Payment_Method','Payment_Method_label']].head()

  Payment_Method  Payment_Method_label
0    Credit Card                     1
1    Credit Card                     1
2     Debit Card                     2
3            UPI                     3
4    Credit Card                     1

In [6]:
df['Region_label']=le.fit_transform(df['Region'])
df[['Region','Region_label']].head()

  Region  Region_label
0  South             2
1  South             2
2  North             1
3  North             1
4   East             0

In [7]:
df_onehot=pd.get_dummies(df,columns=['Tech_Support'])
df_onehot.head()

,Age,Monthly_Charges,Tenure_Months,Contract_Type,Internet_Service,Payment_Method,Region,Churn,Payment_Method_label,Region_label,Tech_Support_No,Tech_Support_Yes
0,56,73.26,5,One-year,DSL,Credit Card,South,0,1,2,True,False
1,69,44.25,65,Two-year,DSL,Credit Card,South,0,1,2,True,False
2,46,46.92,30,Month-to-month,DSL,Debit Card,North,1,2,1,False,True
3,32,57.73,21,Two-year,DSL,UPI,North,0,3,1,False,True
4,60,22.01,70,Month-to-month,DSL,Credit Card,East,0,1,0,True,False

In [8]:
df_onehot=pd.get_dummies(df,columns=['Contract_Type'])
df_onehot.head()

,Age,Monthly_Charges,Tenure_Months,Internet_Service,Payment_Method,Region,Tech_Support,Churn,Payment_Method_label,Region_label,Contract_Type_Month-to-month,Contract_Type_One-year,Contract_Type_Two-year
0,56,73.26,5,DSL,Credit Card,South,No,0,1,2,False,True,False
1,69,44.25,65,DSL,Credit Card,South,No,0,1,2,False,False,True
2,46,46.92,30,DSL,Debit Card,North,Yes,1,2,1,True,False,False
3,32,57.73,21,DSL,UPI,North,Yes,0,3,1,False,False,True
4,60,22.01,70,DSL,Credit Card,East,No,0,1,0,True,False,False